### ISSUE TITLE
Response returned from merchantProfile api has "payPal" as correct spelling while SDK had "paypal". 

### ISSUE THREAD

**Issue by hsinghdeol** [w-pay/sdk-wpay-js#27]
**Describe the bug**

Response returned from this api  "payPal" as correct spelling while SDK had "paypal". 

It causes incorrect check for payPal in merchantProfile.

**To Reproduce**
(https://github.com/w-pay/sdk-wpay-js/blob/357ee946c5ea0620b9fe23b7b5abd37a5d1ab881/types/model/WalletManagementModel/MerchantProfileResponse.d.ts#L31) has spelling as "paypal" while oas spec (https://github.com/w-pay/oas-wpay/blob/b9c510afe4d3f73e30dbcf012f967c59c33cf0b2/dist/wpay-1-0-7.json#L14531) has it as "payPal". 

**Expected behaviour**
Spelling https://github.com/w-pay/sdk-wpay-js/blob/357ee946c5ea0620b9fe23b7b5abd37a5d1ab881/types/model/WalletManagementModel/MerchantProfileResponse.d.ts  nee to be fixed to be "payPal"

**Versions:**
 - `@wpay/sdk` 1.9.0

**Actual response**
<img width="267" alt="Screen Shot 2022-05-02 at 7 04 55 am" src="https://user-images.githubusercontent.com/97861687/166165219-bfb20cbf-3f21-4744-a339-8356c22f1376.png">

**Comment by kierans** [comment]
Thanks @hsinghdeol for the fix 👍
